import { WarpChainAsset, WarpChainName } from '@vleap/warps'

const SolanaChain = WarpChainName.Solana

export const SolanaMainnetTokens: WarpChainAsset[] = [
  {
    chain: SolanaChain,
    identifier: 'SOL',
    name: 'SOL',
    symbol: 'SOL',
    decimals: 9,
    logoUrl: 'https://assets.coingecko.com/coins/images/4128/small/solana.png',
  },
  {
    chain: SolanaChain,
    identifier: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    name: 'USD Coin',
    symbol: 'USDC',
    decimals: 6,
    logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/USD_Coin_icon.png',
  },
  {
    chain: SolanaChain,
    identifier: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
    name: 'Tether USD',
    symbol: 'USDT',
    decimals: 6,
    logoUrl: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
  },
  {
    chain: SolanaChain,
    identifier: 'So11111111111111111111111111111111111111112',
    name: 'Wrapped SOL',
    symbol: 'WSOL',
    decimals: 9,
    logoUrl: 'https://assets.coingecko.com/coins/images/4128/small/solana.png',
  },
  {
    chain: SolanaChain,
    identifier: '3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh',
    name: 'Wrapped Bitcoin',
    symbol: 'WBTC',
    decimals: 8,
    logoUrl: 'https://assets.coingecko.com/coins/images/7598/small/wrapped_bitcoin_wbtc.png',
  },
  {
    chain: SolanaChain,
    identifier: '7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs',
    name: 'Ethereum (Wormhole)',
    symbol: 'ETH',
    decimals: 8,
    logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
  },
  {
    chain: SolanaChain,
    identifier: '7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj',
    name: 'Orca',
    symbol: 'ORCA',
    decimals: 6,
    logoUrl: 'https://assets.coingecko.com/coins/images/17547/small/orca.png',
  },
  {
    chain: SolanaChain,
    identifier: 'mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So',
    name: 'Marinade SOL',
    symbol: 'mSOL',
    decimals: 9,
    logoUrl: 'https://assets.coingecko.com/coins/images/17752/small/mSOL.png',
  },
  {
    chain: SolanaChain,
    identifier: 'J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn',
    name: 'JitoSOL',
    symbol: 'JitoSOL',
    decimals: 9,
    logoUrl: 'https://assets.coingecko.com/coins/images/30168/small/jitosol.png',
  },
  {
    chain: SolanaChain,
    identifier: 'bSo13r4TkiE4KumL71LsHTPpL2suBYJxqsd4P6Bwv11',
    name: 'bSOL',
    symbol: 'bSOL',
    decimals: 9,
    logoUrl: 'https://assets.coingecko.com/coins/images/30167/small/bsol.png',
  },
  {
    chain: SolanaChain,
    identifier: '7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT',
    name: 'UXD Stablecoin',
    symbol: 'UXD',
    decimals: 6,
    logoUrl: 'https://assets.coingecko.com/coins/images/25342/small/uxd.png',
  },
  {
    chain: SolanaChain,
    identifier: 'A9mUU4qviSctJVPJdBJWkb28deg915LYJKrzQ19ji3FM',
    name: 'USD Coin (Wormhole)',
    symbol: 'USDCet',
    decimals: 6,
    logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/USD_Coin_icon.png',
  },
]
