import { WarpChain, WarpChainAsset, WarpChainName } from '@vleap/warps'

const MultiversxChain: WarpChain = WarpChainName.Multiversx

export const MultiversxMainnetTokens: WarpChainAsset[] = [
  {
    chain: MultiversxChain,
    identifier: 'EGLD',
    name: 'eGold',
    symbol: 'EGLD',
    decimals: 18,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/EGLD-000000/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'EGLD-000000',
    name: 'eGold',
    symbol: 'EGLD',
    decimals: 18,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/EGLD-000000/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'SEGLD-3ad2d0',
    name: 'StakedEGLD',
    symbol: 'SEGLD',
    decimals: 18,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/SEGLD-3ad2d0/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'HSEGLD-c13a4e',
    name: 'HatomSEGLD',
    symbol: 'HSEGLD',
    decimals: 8,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/HSEGLD-c13a4e/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'UTK-2f80e9',
    name: 'xMoney UTK',
    symbol: 'UTK',
    decimals: 18,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/UTK-2f80e9/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'USDC-c76f1f',
    name: 'WrappedUSDC',
    symbol: 'USDC',
    decimals: 6,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/USDC-c76f1f/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'WEGLD-bd4d79',
    name: 'WrappedEGLD',
    symbol: 'WEGLD',
    decimals: 18,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/WEGLD-bd4d79/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'HTM-f51d55',
    name: 'Hatom',
    symbol: 'HTM',
    decimals: 18,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/HTM-f51d55/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'MEX-455c57',
    name: 'MEX',
    symbol: 'MEX',
    decimals: 18,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/MEX-455c57/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'WTAO-4f5363',
    name: 'WrappedTAO',
    symbol: 'WTAO',
    decimals: 9,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/WTAO-4f5363/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'HEGLD-d61095',
    name: 'HatomEGLD',
    symbol: 'HEGLD',
    decimals: 8,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/HEGLD-d61095/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'WBTC-5349b3',
    name: 'WrappedBTC',
    symbol: 'WBTC',
    decimals: 8,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/WBTC-5349b3/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'WETH-b4ca29',
    name: 'WrappedETH',
    symbol: 'WETH',
    decimals: 18,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/WETH-b4ca29/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'USH-111e09',
    name: 'HatomUSD',
    symbol: 'USH',
    decimals: 18,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/USH-111e09/icon.png',
  },
  {
    chain: MultiversxChain,
    identifier: 'USDT-f8c08c',
    name: 'WrappedUSDT',
    symbol: 'USDT',
    decimals: 6,
    logoUrl: 'https://tools.multiversx.com/assets-cdn/tokens/USDT-f8c08c/icon.png',
  },
]
